### ISSUE TITLE
Could you please provide concise instruction about how to generate an md doc from alps file in the README.md? 

### ISSUE THREAD

**Issue by nnworkspace** [alps-io/gen-doc#1]
Hi Mr. Amundsen,

I am a reader of your book Design and Build Great Web APIs. In Chapter 5, you mentioned that a Markdown file can be generated from the alps files, but I did not find any How-To instruction. Then I found this GitHub Repo and thought this is probably the right place to ask. Could you please provide concise instruction about how to generate an md doc from an alps file in the README.md in this Repo? 

I prefer to write the alps file in yaml format. Could you please provide the instruction also for yaml format, not only xml or json? And, for the output format, I prefer Markdown format, instead of HTML. 

Best regards,
Ning

**Comment by mamund** [comment]
this project was an experiment for the XML ALPS format and is no longer active. 

i updated the README w/ a simple example to help readers see how it works.

there might be some value here and I'm happy for contributions/PRs on this project.

you might also want to checkout another experiment (`alsp2doc`) that consums JSON and outputs Markdown:
https://github.com/mamund/alps-doc
